version: '3.8'
services:
  draughts-db:
    image: mariadb:10.9 # MySQL.Data crashes with mariadb 10.10, so for now let's stay one version back and see if any of them fixes something.
    container_name: draughts-db
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_INITDB_SKIP_TZINFO: skippls
    volumes:
      - draughts-db-data:/var/lib/mysql
      # Files in this directory are executed in alphabetical order when initializing
      - ./draughts-db/init.sql:/docker-entrypoint-initdb.d/aa-init.sql
    ports:
      - 52506:3306 # SQL Port

  # Adminer is a web tool used to manage databases
  adminer:
    image: adminer
    container_name: draughts-adminer
    restart: "no"
    environment:
      ADMINER_DEFAULT_SERVER: draughts-db
    ports:
      - 52580:8080 # Webinterface: HTTP

volumes:
  draughts-db-data:
