name: DDD Draughts CI pipeline

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Build backend
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore backend dependencies
      run: dotnet restore
    - name: Build backend
      run: dotnet build --no-restore

    # Build frontend
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install frontend dependencies
      run: >
        cd Draughts.Frontend/
        && npm ci
        && cd ../
    - name: Build frontend
      run: >
        cd Draughts.Frontend/
        && npm run build:prod
        && cd ../

    # Setup database for the tests
    - name: Start database
      run: ./run-dev.sh start
    - name: Init database
      run: >
        cd Draughts.Command/
        && dotnet run --project Draughts.Command.csproj data:essential data:dummy
        && cd ../

    # Run all tests
    - name: Run unit tests
      run: >
        dotnet test
        --no-build
        --verbosity normal
        --filter FullyQualifiedName~Draughts.Test
    - name: Run query builder tests
      run: >
        dotnet test
        --no-build
        --verbosity normal
        --filter FullyQualifiedName~SqlQueryBuilder.Test
    - name: Run database backend tests
      run: >
        dotnet test
        --no-build
        --verbosity normal
        --filter FullyQualifiedName~Draughts.IntegrationTest
