name: DDD Draughts CI pipeline

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore backend dependencies
      run: dotnet restore
    - name: Build backend
      run: dotnet build --no-restore

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Build frontend
      run: >
        cd Draughts.Frontend/
        && npm ci
        && cd ../
    - name: Build frontend
      run: >
        cd Draughts.Frontend/
        && npm run build:prod
        && cd ../

    - name: Start database
      run: ./run-dev.sh start
    - name: Init database
      run: >
        cd Draughts.Command/
        && dotnet run --project Draughts.Command.csproj data:essential data:dummy
        && cd ../

    - name: Run backend tests
      run: dotnet test --no-build --verbosity normal
